# Generated by Django 2.2.3 on 2019-08-06 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('An', models.CharField(blank=True, max_length=100, verbose_name='资产编号')),
                ('Sn', models.CharField(blank=True, max_length=50, verbose_name='硬件SN号')),
                ('ServerName', models.CharField(blank=True, max_length=50, verbose_name='服务器名称')),
                ('SysName', models.CharField(blank=True, max_length=50, verbose_name='系统全称')),
                ('Use', models.CharField(blank=True, max_length=50, verbose_name='用途')),
                ('Location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('Cabinet', models.PositiveIntegerField(verbose_name='机柜')),
                ('BrandModels', models.CharField(blank=True, max_length=50, verbose_name='品牌型号')),
                ('PurchaseDate', models.CharField(blank=True, max_length=300, verbose_name='购入日期')),
                ('Head', models.DateTimeField(default=datetime.datetime.now, verbose_name='负责人')),
                ('Ipaddress', models.DateTimeField(default=datetime.datetime.now, verbose_name='ip地址')),
                ('WDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='维保日期')),
                ('Undernet', models.DateTimeField(default=datetime.datetime.now, verbose_name='资产状态')),
                ('Comment', models.DateTimeField(default=datetime.datetime.now, verbose_name='备注')),
                ('Modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
            },
        ),
        migrations.CreateModel(
            name='ServerHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverid', models.IntegerField(verbose_name='资产ID')),
                ('zctype', models.CharField(max_length=20, verbose_name='资产类型')),
                ('An', models.CharField(blank=True, max_length=100, verbose_name='资产编号')),
                ('Sn', models.CharField(blank=True, max_length=50, verbose_name='硬件SN号')),
                ('ServerName', models.CharField(blank=True, max_length=50, verbose_name='服务器名称')),
                ('SysName', models.CharField(blank=True, max_length=50, verbose_name='系统全称')),
                ('Use', models.CharField(blank=True, max_length=50, verbose_name='用途')),
                ('Location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('Cabinet', models.PositiveIntegerField(verbose_name='机柜')),
                ('BrandModels', models.CharField(blank=True, max_length=50, verbose_name='品牌型号')),
                ('PurchaseDate', models.CharField(blank=True, max_length=300, verbose_name='购入日期')),
                ('Head', models.DateTimeField(default=datetime.datetime.now, verbose_name='负责人')),
                ('Ipaddress', models.DateTimeField(default=datetime.datetime.now, verbose_name='ip地址')),
                ('WDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='维保日期')),
                ('Undernet', models.DateTimeField(default=datetime.datetime.now, verbose_name='资产状态')),
                ('Comment', models.DateTimeField(default=datetime.datetime.now, verbose_name='备注')),
                ('Modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '资产历史表',
                'verbose_name_plural': '资产历史表',
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zctype', models.CharField(max_length=20, verbose_name='资产类型')),
            ],
            options={
                'verbose_name': '资产类型表',
                'verbose_name_plural': '资产类型表',
            },
        ),
    ]
