# Generated by Django 2.2.3 on 2020-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_zcsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverhis',
            name='zcsn',
            field=models.CharField(blank=True, max_length=15, verbose_name='资产编号'),
        ),
    ]
